Repository iron-vault-plugin/iron-vault, pull requests merged in 2024-06, with the labels that each got.

#172 add option to inline tracks and clocks on creation
  src/clocks/commands.ts
  src/mechanics/css/details.css
  src/mechanics/node-builders.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/tracks/commands.ts
Labels: enhancement

#176 Actually have categories in releases according to PR labels
  .github/release.yml
Labels: technical improvement

#177 shiny new plugin icon
  LICENSE.md
  src/commands.ts
  src/index.ts
  src/sidebar/sidebar-view.ts
Labels: feature

#179 update URLs to reflect new repo location
  CONTRIBUTING.md
  README.md
  docs-built/blocks/about-blocks.html
  docs-built/blocks/asset-blocks.html
  docs-built/blocks/character-blocks.html
  docs-built/blocks/clock-blocks.html
  docs-built/blocks/mechanics-blocks.html
  docs-built/blocks/moves-blocks.html
  docs-built/blocks/oracles-blocks.html
  docs-built/blocks/track-blocks.html
  docs-built/commands/about-commands.html
  docs-built/commands/add-asset-to-character.html
  docs-built/commands/advance-a-clock.html
  docs-built/commands/advance-a-progress-track.html
  docs-built/commands/ask-the-oracle.html
  docs-built/commands/burn-momentum.html
  docs-built/commands/create-a-clock.html
  docs-built/commands/create-a-progress-track.html
  docs-built/commands/create-new-character.html
  docs-built/commands/generate-an-entity.html
  docs-built/commands/make-a-move.html
  docs-built/commands/show-all-commands.html
  docs-built/commands/show-sidebar.html
  docs-built/commands/suffer-on-a-meter.html
  docs-built/commands/take-on-a-meter.html
  docs-built/commands/toggle-displaying-mechanics.html
  docs-built/entities/about-entities.html
  docs-built/entities/assets.html
  docs-built/entities/characters.html
  docs-built/entities/clocks.html
  docs-built/entities/delves.html
  docs-built/entities/derelicts.html
  docs-built/entities/factions.html
  docs-built/entities/locations-and-settlements.html
  docs-built/entities/moves.html
  docs-built/entities/npcs.html
  docs-built/entities/oracles.html
  docs-built/entities/progress-tracks.html
  docs-built/entities/sectors.html
  docs-built/entities/truths.html
  docs-built/entities/vaults.html
  docs-built/index.html
  docs-built/lib/html/file-tree.html
  docs-built/lib/metadata.json
  docs-built/lib/rss.xml
  docs-built/lib/search-index.json
  docs-built/lib/styles/other-plugins.css
  docs-built/other-features/api.html
  docs-built/other-features/css-tweaks.html
  docs-built/other-features/debug-logging.html
  docs-built/other-features/ribbon-button.html
  docs-built/other-features/rulesets.html
  docs-built/other-features/settings.html
  docs-built/other-features/sidebar.html
  docs-built/other-features/special-links.html
  docs/.obsidian/plugins/webpage-html-export/data.json
  docs/.obsidian/workspace.json
  docs/index.md
  manifest.json
Labels: documentation

#181 change default settings for mechanic blocks
  docs-built/lib/metadata.json
  docs-built/lib/rss.xml
  docs-built/lib/search-index.json
  docs-built/other-features/settings.html
  docs/.obsidian/workspace.json
  docs/Other Features/Settings.md
  src/settings/index.ts
  src/settings/ui.ts
Labels: documentation, feature

#183 fix grid issue with xp earned
  docs/Other Features/Settings.md
  src/characters/css/character-info.css
Labels: bug

#189 stop using checkmark for matches
  src/mechanics/css/dlist-clock.css
  src/mechanics/css/dlist-progress.css
  src/mechanics/css/dlist-shared.css
  src/mechanics/css/dlist-track.css
  src/mechanics/css/summary.css
  src/mechanics/mechanics-blocks.ts
  test-vault/Journals/Chapter 01.md
  test-vault/Journals/Chapter 02.md
Labels: polish

#170 add support for truths
  docs/.obsidian/workspace.json
  docs/Blocks/About Blocks.md
  docs/Blocks/Truth Blocks.md
  docs/Commands/Generate Truths.md
  docs/Entities/Truths.md
  src/commands.ts
  src/datastore.ts
  src/datastore/datasworn-indexer.ts
  src/index.ts
  src/styles.css
  src/truths/command.ts
  src/truths/css/truths.css
  src/truths/truth-block.ts
  test-vault/Journals/Chapter 01.md
  test-vault/Truths.md
Labels: feature

#192 fix truth blocks
  src/truths/truth-block.ts
  test-vault/Truths.md
Labels: bug

#193 set the cursor position after interaction with truth blocks
  src/truths/truth-block.ts
Labels: polish

#194 Style mechanics blocks so they stand out more even without move nodes
  src/mechanics/css/details.css
  src/mechanics/css/dlist-add.css
  src/mechanics/css/dlist-meter.css
  src/mechanics/css/dlist-progress.css
  src/mechanics/css/dlist-roll.css
  src/mechanics/css/dlist-shared.css
  src/mechanics/css/dlist-xp.css
  src/mechanics/css/mechanics.css
  src/mechanics/css/move.css
  test-vault/Journals/Chapter 01.md
Labels: polish

#198 rename 'mechanics' block to 'iron-vault-mechanics'
  docs/.obsidian/workspace.json
  docs/Blocks/About Blocks.md
  docs/Blocks/Mechanics Blocks.md
  src/mechanics/editor.ts
  src/mechanics/mechanics-blocks.ts
  src/utils/editor.test.ts
  src/utils/editor.ts
Labels: polish

#199 new, shiny asset picker
  src/characters/commands.ts
  src/characters/css/asset-list.css
  src/characters/css/characters.css
  src/sidebar/css/sidebar.css
  src/sidebar/css/tab-content-shared.css
  src/sidebar/moves.ts
Labels: feature

#200 render asset requirement as markdown
  src/characters/asset-card.ts
Labels: bug

#205 use smart quotes for callsigns to avoid Windows filename issue
  src/entity/specs.ts
Labels: bug

#206 insert extra newline between Truths
  src/truths/command.ts
Labels: polish

#207 include the truth summary in the preview
  src/truths/truth-block.ts
Labels: polish

#210 Use loglevel package for controlling logging
  docs/Other Features/Debug Logging.md
  package.json
  pnpm-lock.yaml
  src/api.ts
  src/characters/character-block.ts
  src/clocks/commands.ts
  src/datastore.ts
  src/datastore/data-indexer.ts
  src/datastore/parsers/datasworn/oracles.ts
  src/entity/modal.ts
  src/index.ts
  src/indexer/indexer.ts
  src/indexer/manager.ts
  src/logger.ts
  src/moves/action/adds-modal.ts
  src/moves/action/index.ts
  src/moves/block.ts
  src/oracles/command.ts
  src/sidebar/oracles.ts
  src/tracks/commands.ts
  src/utils/obsidian.ts
  src/utils/suggest.ts
  src/utils/ui/prompt.ts
Labels: technical improvement

#212 get rid of lookbehinds
  src/datastore/parsers/table.ts
  src/utils/strings.ts
Labels: bug

#217 generate split character sheet by default
  src/characters/commands.ts
Labels: polish

#218 add command to easily insert OOC comments
  src/commands.ts
  src/mechanics/commands.ts
Labels: feature

#219 add command to insert spoilers
  src/commands.ts
Labels: feature

#223 Add progress track completion command
  src/characters/action-context.ts
  src/characters/commands.ts
  src/characters/meter-commands.ts
  src/commands.ts
  src/mechanics/node-builders.ts
  src/moves/action/index.ts
  src/tracks/commands.ts
Labels: feature

#226 make sure truth widget buttons are tall and wide enough
  src/truths/css/truths.css
Labels: bug

#209 Write a full Player's Guide and Getting Started guide
  README.md
  docs/.obsidian/workspace.json
  docs/Other Features/Callouts.md
  docs/Player's Guide/Getting Started/Begin Your Adventure.md
  docs/Player's Guide/Getting Started/Build a Starting Sector.md
  docs/Player's Guide/Getting Started/Choose Your Truths.md
  docs/Player's Guide/Getting Started/Create Your Character.md
  docs/Player's Guide/Getting Started/Initial Setup.md
  docs/Player's Guide/Getting Started/Your First Campaign.md
  docs/Player's Guide/index.md
  docs/Support/img/Player's Guide/asset-picker-card.png
  docs/Support/img/Player's Guide/asset-picker-expanded.png
  docs/Support/img/Player's Guide/asset-picker-initial.png
  docs/Support/img/Player's Guide/background-vow-inserted.png
  docs/Support/img/Player's Guide/background-vow-window.png
  docs/Support/img/Player's Guide/backstory-mechanics-block.png
  docs/Support/img/Player's Guide/backstory-prompts-popup.png
  docs/Support/img/Player's Guide/brat-menu.png
  docs/Support/img/Player's Guide/callsign-pronouns.png
  docs/Support/img/Player's Guide/character-description.png
  docs/Support/img/Player's Guide/character-frontmatter.png
  docs/Support/img/Player's Guide/character-sheet.png
  docs/Support/img/Player's Guide/condition-meters.png
  docs/Support/img/Player's Guide/gearing-up.png
  docs/Support/img/Player's Guide/generate-truths-menu.png
  docs/Support/img/Player's Guide/generated-truths-page.png
  docs/Support/img/Player's Guide/getting-started-initial.png
  docs/Support/img/Player's Guide/session-0.png
  docs/Support/img/Player's Guide/sidebar-starship-history.png
  docs/Support/img/Player's Guide/starship-asset.png
  docs/Support/img/Player's Guide/stats-edited.png
  docs/Support/img/character-sheet.png
  docs/Support/img/ribbon-icon.png
  docs/index.md
Labels: documentation

#221 allow editing of all clock and track fields through widget
  src/clocks/clock-block.ts
  src/clocks/clock-create-modal.ts
  src/clocks/clock-file.ts
  src/clocks/clock.test.ts
  src/clocks/clock.ts
  src/clocks/css/clocks.css
  src/tracks/css/tracks.css
  src/tracks/track-block.ts
Labels: feature

#230 get planet and settlement entities working
  src/datastore/datasworn-indexer.ts
  src/entity/command.ts
  src/entity/modal.ts
  src/entity/specs.ts
Labels: feature

#231 messed up region oracle table oops
  src/datastore/datasworn-indexer.ts
Labels: bug

#232 write a starting sector guide
  docs/.obsidian/workspace.json
  docs/Entities/Creatures.md
  docs/Entities/Locations and Settlements.md
  docs/Entities/Planets.md
  docs/Entities/Sectors.md
  docs/Entities/Settlements.md
  docs/Entities/index.md
  docs/Player's Guide/Getting Started/Build a Starting Sector.md
  docs/Player's Guide/Getting Started/Create Your Character.md
  docs/Player's Guide/Getting Started/Initial Setup.md
  docs/Support/img/Player's Guide/completed-connection.png
  docs/Support/img/Player's Guide/edited-planet-settlement.png
  docs/Support/img/Player's Guide/edited-settlement-planet.png
  docs/Support/img/Player's Guide/embedded-connection-track.png
  docs/Support/img/Player's Guide/finalized-sector.png
  docs/Support/img/Player's Guide/first-settlement.png
  docs/Support/img/Player's Guide/generate-entity-modal-filled.png
  docs/Support/img/Player's Guide/generate-entity-modal.png
  docs/Support/img/Player's Guide/generated-connection.png
  docs/Support/img/Player's Guide/generated-planets.png
  docs/Support/img/Player's Guide/new-progress-trap-modal.png
  docs/Support/img/Player's Guide/planet-with-star-row.png
  docs/Support/img/Player's Guide/sector-initial.png
  docs/Support/img/Player's Guide/sector-region.png
  docs/Support/img/Player's Guide/sector-trouble.png
  docs/Support/img/Player's Guide/sector-with-passages.png
  docs/Support/img/Player's Guide/sector-with-stuff.png
  docs/Support/img/Player's Guide/stellar-object-oracle-rolls.png
  docs/Support/img/Player's Guide/zoomed-in-settlement.png
Labels: documentation

#236 clearer styling for spoilers
  src/styles.css
  test-vault/Journals/Chapter 02.md
Labels: polish

#238 reorder commands a bit
  src/commands.ts
Labels: polish

#249 add support for toggling ironsworn and starforged rules on and off
  package.json
  pnpm-lock.yaml
  src/assets/asset-block.ts
  src/assets/asset-card.ts
  src/assets/asset-modal.ts
  src/assets/asset-picker-modal.ts
  src/assets/css/asset-card.css
  src/assets/css/asset-list.css
  src/assets/css/assets.css
  src/assets/link-override.ts
  src/characters/character-block.ts
  src/characters/commands.ts
  src/datastore.ts
  src/datastore/datasworn-indexer.ts
  src/index.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/sidebar/css/moves.css
  src/sidebar/moves.ts
  src/sidebar/sidebar-view.ts
  src/styles.css
Labels: feature

#252 fix a few things with IS support to make the experience smoother
  src/assets/asset-picker-modal.ts
  src/characters/character-block.ts
  src/settings/ui.ts
  src/sidebar/moves.ts
Labels: bug

#254 enable switching rulesets without having to reload
  src/assets/asset-card.ts
  src/index.ts
  src/oracles/render.ts
  src/settings/ui.ts
Labels: bug

#222 graphical dice roller
  esbuild.config.js
  package.json
  pnpm-lock.yaml
  src/api.ts
  src/datastore.ts
  src/datastore/datasworn-indexer.ts
  src/datastore/parsers/datasworn/oracles.ts
  src/entity/modal.ts
  src/index.ts
  src/iron-vault.d.ts
  src/model/oracle.ts
  src/model/rolls.ts
  src/moves/action/index.ts
  src/oracles/command.ts
  src/oracles/modal.ts
  src/oracles/render.ts
  src/oracles/roller.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/styles.css
  src/truths/truth-block.ts
  src/utils/dice-group.ts
  src/utils/dice-overlay.ts
  src/utils/dice.test.ts
  src/utils/dice.ts
Labels: feature

#259 fix issue with selects not properly rendering their values in asset c…
  src/assets/asset-card.ts
Labels: bug

#260 need to async-wait for entity rolls
  src/entity/modal.ts
Labels: bug

#264 add config support for dice colors
  src/datastore/parsers/datasworn/oracles.ts
  src/moves/action/index.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/truths/truth-block.ts
  src/utils/dice-group.ts
  src/utils/dice.ts
Labels: feature

#266 rewrite asset files on every load
  src/utils/dice-overlay.ts
Labels: bug

#267 Allow configuration of filename/dir for entity generation, just like with clocks/tracks
  package.json
  pnpm-lock.yaml
  src/clocks/clock-create-modal.ts
  src/entity/command.ts
  src/entity/modal.ts
  src/entity/specs.ts
Labels: polish

#268 add support for separate config for challenge dice, cursed die config…
  src/moves/action/index.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/utils/dice.ts
Labels: feature

#269 filter entities by ruleset and add an IS ent
  src/entity/command.ts
  src/entity/specs.ts
Labels: feature

#274 make dice bigger on mobile
  src/iron-vault.d.ts
  src/utils/dice-overlay.ts
Labels: bug

#278 try to use visibility instead of pointer-events to see if it helps wi…
  src/styles.css
Labels: bug

#275 Add support for initiative/position
  docs/.obsidian/workspace.json
  docs/Blocks/Mechanics Blocks.md
  src/characters/character-block.ts
  src/characters/commands.ts
  src/characters/lens.test.ts
  src/characters/lens.ts
  src/datastore.ts
  src/mechanics/css/dlist-initiative.css
  src/mechanics/css/mechanics.css
  src/mechanics/mechanics-blocks.ts
  src/rules/ruleset.ts
  test-vault/Journals/Chapter 02.md
Labels: feature

#287 add settings button to reset settings to their defaults
  src/settings/index.ts
  src/settings/ui.ts
Labels: feature

#290 add die reroll command
  src/commands.ts
  src/mechanics/mechanics-blocks.ts
  src/moves/action/action-modal.ts
  test-vault/Journals/Chapter 02.md
Labels: feature

#288 Add command for changing initiative/position
  src/characters/commands.ts
  src/commands.ts
  src/mechanics/node-builders.ts
Labels: feature

#297 properly select progress track rank on load
  src/tracks/track-block.ts
Labels: bug

#298 change challenge die colors in mechanics blocks according to settings
  src/mechanics/css/dlist-shared.css
  src/mechanics/mechanics-blocks.ts
  src/settings/ui.ts
Labels: feature

#306 nicer dice, some fixes
  package.json
  pnpm-lock.yaml
  src/iron-vault.d.ts
  src/utils/dice-overlay.ts
  src/utils/dice.ts
Labels: feature

#307 give initiative a bit of a margin
  src/characters/css/character-info.css
Labels: polish

#311 allow text selection inside modals
  src/assets/asset-modal.ts
  src/entity/modal.ts
  src/moves/move-modal.ts
  src/oracles/oracle-modal.ts
  src/styles.css
Labels: bug

#313 add clickable stat buttons to move modal
  src/characters/css/stats.css
  src/moves/action/index.ts
  src/moves/css/move-modal.css
  src/moves/move-modal.ts
  src/styles.css
Labels: feature

#315 add support for passing a character file name as an 'argument' to cha…
  docs/.obsidian/workspace.json
  docs/Blocks/Character Blocks.md
  src/characters/character-block.ts
Labels: feature

#333 add button to roll move-related oracles directly from the move modal
  src/moves/move-modal.ts
Labels: feature

#334 Allow loading Delve and SI expansion content
  LICENSE.md
  docs/Other Features/Rulesets and Homebrew.md
  package.json
  pnpm-lock.yaml
  src/datastore.ts
  src/index.ts
  src/indexer/manager.ts
  src/settings/index.ts
  src/settings/ui.ts
  test-vault/Homebrew/delve.json
Labels: feature

#336 Use a view for migration process
  src/commands.ts
  src/index.ts
  src/migrate/command.ts
  src/migrate/css/migrate.css
  src/migrate/manager.ts
  src/migrate/migration-view.ts
Labels: polish

#341 Fix bad substitution during migration
  src/migrate/migration-0_0_10-0_1_0.test.ts
  src/migrate/migration-0_0_10-0_1_0.ts
Labels: bug

#342 Migrate page buttons look bad on mobile
  src/migrate/css/migrate.css
  src/migrate/migration-view.ts
Labels: polish

#344 Handle missing character error on first load
  src/sidebar/character.ts
Labels: bug

#346 only clear dice after they're done rolling
  src/utils/dice-overlay.ts
Labels: bug

#347 strip markdown from track/clock node links
  src/clocks/commands.ts
  src/clocks/select-clock.ts
  src/commands.ts
  src/mechanics/node-builders.ts
  src/moves/action/index.ts
  src/tracks/commands.ts
  src/tracks/select.ts
  src/utils/strip-markdown.ts
Labels: bug

#343 Use sensible defaults for stats, meters, and tracks when loading characters
  src/characters/lens.test.ts
  src/characters/lens.ts
Labels: feature

#348 Allow skipping action move rolls
  docs/Commands/Make a move.md
  src/moves/action/index.ts
Labels: feature

#345 add support for cursed die
  .gitignore
  docs/.obsidian/workspace.json
  docs/Entities/Oracles.md
  docs/Other Features/Special Links.md
  src/datastore/parsers/datasworn/oracles.ts
  src/mechanics/css/dlist-oracle.css
  src/mechanics/mechanics-blocks.ts
  src/mechanics/node-builders.ts
  src/model/oracle.ts
  src/model/rolls.ts
  src/oracles/command.ts
  src/oracles/modal.ts
  src/settings/index.ts
  src/settings/ui.ts
Labels: feature, ruleset: sundered isles

#352 allow disabling and rerolling cursed die
  src/datastore/parsers/datasworn/oracles.ts
  src/model/rolls.ts
  src/oracles/modal.ts
  src/settings/index.ts
  src/settings/ui.ts
Labels: polish
