Repository iron-vault-plugin/iron-vault, pull requests merged in 2024-07, with the labels that each got.

#354 Show source ruleset when using make a move command
  src/datastore.ts
  src/datastore/datasworn-indexer.ts
  src/moves/action/index.ts
  src/oracles/command.ts
Labels: polish

#356 play around with asset list alignment and move add asset button out
  src/characters/character-block.ts
  src/characters/css/assets.css
Labels: polish

#357 be clearer about Roll All vs individual rolls
  src/sidebar/css/oracles.css
  src/sidebar/oracles.ts
Labels: polish

#358 support assets with ability-level options a bit better
  src/assets/asset-card.ts
  src/assets/css/asset-card.css
Labels: polish

#365 Give asset meters unique keys and labels
  src/characters/action-context.ts
  src/characters/assets.ts
  src/characters/display.ts
  src/characters/lens.test.ts
  src/characters/lens.ts
  src/characters/meter-commands.ts
  src/moves/action/index.ts
  src/utils/ensure-unique.ts
  test-vault/characters/Ash Barlowe.md
Labels: bug

#364 address Obsidian dev feedback
  .gitignore
  data.json
  package.json
  pnpm-lock.yaml
  src/assets/asset-picker-modal.ts
  src/characters/character-block.ts
  src/characters/commands.ts
  src/clocks/clock-create-modal.ts
  src/docs/docs-view.ts
  src/entity/modal.ts
  src/entity/specs.ts
  src/index.ts
  src/mechanics/mechanics-blocks.ts
  src/moves/action/action-modal.ts
  src/moves/block.ts
  src/moves/wrapper.ts
  src/tracks/progress-create.ts
  src/utils/ui/settings/folder.ts
  src/utils/ui/settings/generic-text-suggest.ts
  src/utils/ui/suggest.ts
Labels: polish

#366 use defaults defined by the asset itself when rendering the sample as…
  src/assets/asset-card.ts
  src/assets/asset-modal.ts
  src/assets/asset-picker-modal.ts
Labels: bug

#367 Update entities to datasworn 0.1.0
  src/entity/command.ts
  src/entity/modal.ts
  src/entity/specs.ts
Labels: bug

#371 Handle renames in tracked entity blocks
  src/characters/character-block.ts
  src/clocks/clock-block.ts
  src/indexer/index-impl.ts
  src/indexer/index-interface.ts
  src/indexer/indexer.ts
  src/indexer/manager.ts
  src/tracks/track-block.ts
  src/utils/ui/tracked-entity-renderer.ts
Labels: bug

#368 add support for multiple characters.
  docs/Commands/Make an action roll.md
  docs/Commands/Pick active character.md
  docs/Commands/index.md
  docs/Entities/Characters.md
  docs/Other Features/Multiplayer.md
  docs/Other Features/Settings.md
  docs/index.md
  src/api.ts
  src/assets/asset-picker-modal.ts
  src/character-tracker.ts
  src/characters/action-context.ts
  src/characters/character-block.ts
  src/characters/commands.ts
  src/characters/css/character-info.css
  src/characters/meter-commands.ts
  src/commands.ts
  src/index.ts
  src/mechanics/actor.test.ts
  src/mechanics/actor.ts
  src/mechanics/css/actor.css
  src/mechanics/css/mechanics.css
  src/mechanics/editor.ts
  src/mechanics/mechanics-blocks.ts
  src/mechanics/operations.test.ts
  src/mechanics/operations.ts
  src/moves/action/action-modal.ts
  src/moves/action/format.ts
  src/moves/action/index.ts
  src/settings/index.ts
  src/settings/local.ts
  src/settings/ui.ts
  src/sidebar/character.ts
  src/sidebar/sidebar-view.ts
  test-vault/Journals/Chapter 02.md
Labels: feature

#379 Link handler should use raw href
  src/link-handler.ts
Labels: bug

#380 Safer handling of missing local settings file
  src/settings/local.ts
Labels: bug

#381 Reroll should work with actor nodes
  src/moves/action/action-modal.ts
Labels: bug

#374 add entities for sundered isles
  data/sundered-isles.supplement.json
  data/sundered-isles.supplement.yaml
  package.json
  src/datastore.ts
  src/entity/command.ts
  src/entity/specs.ts
  src/sidebar/oracles.ts
Labels: feature

#385 document the position/initiative change command and rename it
  docs/Commands/Change position or initiative.md
  docs/Commands/index.md
  src/commands.ts
Labels: documentation

#386 style oracle tables a bit nicer
  src/moves/move-modal.ts
  src/oracles/css/oracles.css
  src/oracles/oracle-modal.ts
  src/oracles/render.ts
Labels: polish

#390 fix issue with track-type not being saved
  src/tracks/commands.ts
  src/tracks/progress-create.ts
Labels: bug

#391 Added Starforged Settlement Generator
  src/entity/specs.ts
Labels: feature

#392 Fix bug when selecting suggested folder
  src/clocks/clock-create-modal.ts
  src/entity/modal.ts
  src/settings/ui.ts
  src/tracks/progress-create.ts
  src/truths/command.ts
  src/utils/ui/settings/folder.ts
Labels: bug

#396 set up new icon and logos in UI
  media/ironvault_icon_100x100.svg
  src/index.ts
  src/settings/ui.ts
  src/styles.css
Labels: polish

#398 tweak styles for ruleset images in settings
  src/styles.css
Labels: polish

#410 add player name and manual xp fields
  src/characters/character-block.ts
  src/characters/css/character-info.css
  src/characters/lens.test.ts
  src/characters/lens.ts
Labels: feature

#412 disambiguate truths by ID
  src/truths/command.ts
  src/truths/truth-block.ts
Labels: bug

#413 stop writing out starforged truths if SI is enabled
  src/truths/command.ts
Labels: polish

#415 move mechanics rendering over to lit-html
  src/mechanics/css/details.css
  src/mechanics/css/mechanics.css
  src/mechanics/css/oracle-group.css
  src/mechanics/mechanics-blocks.ts
Labels: technical improvement

#416 add deletion support to mechanics blocks and individual nodes
  src/mechanics/mechanics-blocks.ts
Labels: feature

#419 hack in incidental vehicles
  data/starforged.supplement.json
  data/starforged.supplement.yaml
  data/sundered-isles.supplement.json
  data/sundered-isles.supplement.yaml
Labels: feature

#404 Added Support for Multiple Rolls in Enitity Generation
  src/datastore/parsers/datasworn/oracles.ts
  src/entity/modal.ts
  src/model/oracle.ts
Labels: feature

#423 add directive for spitting out obsidian settings in templates
  src/utils/ui/directives.ts
Labels: technical improvement

#425 Basic documentation for campaigns system
  docs/Campaigns.md
  docs/Commands/Create a new campaign.md
  docs/Commands/Pick active character.md
  docs/Entities/Characters.md
  docs/Entities/index.md
  docs/Player's Guide/Getting Started/01 - Initial Setup.md
  docs/Player's Guide/Getting Started/02 - Your First Campaign.md
  docs/Support/Empty campaign.md
  docs/Support/img/Create a new campaign.png
  docs/Support/img/Onboarding screen.png
  docs/Support/img/Onboarding tab.png
  docs/index.md
Labels: documentation

#428 add ruleset info to assets/moves/oracles
  src/assets/asset-card.ts
  src/assets/css/asset-card.css
  src/moves/css/move-modal.css
  src/moves/move-modal.ts
  src/oracles/css/oracles.css
  src/oracles/oracle-modal.ts
Labels: polish

#433 sortable mechanics block entries
  src/mechanics/mechanics-blocks.ts
Labels: feature

#434 update sundered-isles package name
  package.json
  pnpm-lock.yaml
  src/datastore.ts
  src/mechanics/mechanics-blocks.ts
Labels: technical improvement

#432 Split up the graphic dice settings for oracle and action action dice
  src/datastore/parsers/datasworn/oracles.ts
  src/moves/action/action-modal.ts
  src/moves/action/index.ts
  src/oracles/modal.ts
  src/settings/index.ts
  src/settings/ui.ts
  src/truths/truth-block.ts
  src/utils/dice-group.ts
  src/utils/dice-overlay.ts
  src/utils/dice.test.ts
  src/utils/dice.ts
Labels: polish

#442 fix issues with node dragging
  src/mechanics/mechanics-blocks.ts
Labels: bug

#439 SI faction entities
  src/entity/specs.ts
Labels: feature

#443 support more thorough scaffolding on campaign creation
  src/campaigns/commands.ts
  src/campaigns/ui/new-campaign-modal.ts
  src/characters/commands.ts
  src/truths/command.ts
Labels: feature

#444 move to datasworn@next packages and update licensing
  LICENSE.md
  package.json
  pnpm-lock.yaml
Labels: technical improvement

#445 Fixed SI Settlement Entity
  src/entity/specs.ts
Labels: bug

#451 add faction influence grid generator
  src/commands.ts
  src/constants.ts
  src/factions/commands.ts
  src/factions/grid-creation-modal.ts
Labels: feature
